### ISSUE TITLE
Support DELETE FROM statements

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#16]
It is very often required to execute `DELETE FROM` SQL statement, although it's possible to use `typeof` and `nameof` operators without major performance hit, it still would be nice to support those statements with LINQ.

Something like:

```cs
// Delete all objects from Person table.
Objects<Person>.Delete();

// Delete objects from Person table if Name equals to test.
Objects<Person>.Delete(x => x.Name == "test");
```

**Comment by un-tone** [comment]
Closing as done

**Comment by miyconst** [comment]
Does `Delete`  method support the same filtering predicates as `Where` does?

**Comment by un-tone** [comment]
Yes. I added additional tests for this feature.
