### ISSUE TITLE
Implement object.Equals support

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#35]
When comparing CLR classes the `==` operator is [not applicable](https://docs.starcounter.io/guides/database/comparing-database-objects#comparison-between-instances), instead `object.Equals` method should be used. `Starcounter.Linq` should also support this construction.

**Example**:

```cs
Company company = new Company();
DbLinq.Objects<Person>().Where(x => x.Company.Equals(company)).ToList();
```

**Comment by un-tone** [comment]
Closing as done.
