### ISSUE TITLE
Starcounter.Linq.Queryable.GetEnumerator throws System.NullReferenceException

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#37]
On this [line](https://github.com/Starcounter/Starcounter.Linq/blob/master/src/Starcounter.Linq/Queryable.cs#L35) `Starcounter.Linq.Queryable` throws `System.NullReferenceException: Object reference not set to an instance of an object.` if `Provider.Execute<IEnumerable>(Expression)` returns `null`.

**Comment by miyconst** [comment]
Adding a null reference check solves this issue, but leads to another one - [Typed JSON property binding does not work with LINQ queries](https://github.com/Starcounter/Starcounter.Linq/issues/38).

```cs
IEnumerator IEnumerable.GetEnumerator() => Provider.Execute<IEnumerable>(Expression)?.GetEnumerator();
```

**Comment by un-tone** [comment]
The issue is fixed with https://github.com/Starcounter/Starcounter.Linq/pull/39 PR.
So I think we should not add a null reference check here
```cs
IEnumerator IEnumerable.GetEnumerator() => Provider.Execute<IEnumerable>(Expression)?.GetEnumerator();
```
and the issue can be closed after merging #39. Do you agree, @miyconst?

**Comment by miyconst** [comment]
Okay. Let's close it after https://github.com/Starcounter/Starcounter.Linq/pull/39 is merged.

**Comment by un-tone** [comment]
Closing..
