### ISSUE TITLE
Update to support Starcounter Odessa (2.4) and release a compatible NuGet package

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#41]
Currently `Starcounter.Linq` NuGet package can be installed into a Starcounter Odessa (2.4) solution. It will compile, but it will crash at run time due to binary incompatibility between the Starcounter versions.

The best thing we can do right now, is to release another NuGet package with Starcounter Odessa (2.4) and add compatibility description.

**Comment by un-tone** [comment]
@miyconst Should I create a separate branch for v2.4, or after these changes, we will stop support SC 2.3 for this library?

**Comment by miyconst** [comment]
@un-tone please create a separate branch called `develop`. The `master` branch should always be merged to `develop`. Once we drop support of Starcounter `2.3` the `develop` branch will become the master.

Starcounter `2.3` compatibility is required for at least half a year from now.

**Comment by un-tone** [comment]
@miyconst If I understood correctly, it should be a completely separate package. Do you have any suggestions how it should be called? Maybe we have some convention for it?

**Comment by miyconst** [comment]
Unfortunately we can't release the same package targeting different Starcounter versions, so the only option is to bump the major package version and provide proper description with Starcounter version compatibility.

**Comment by un-tone** [comment]
Ah, okay, got it.

**Comment by un-tone** [comment]
I have released Starcounter.Linq 2.0: <https://github.com/Starcounter/Starcounter.Linq/releases/tag/2.0.0>
and published the NuGet package: <https://www.nuget.org/packages/Starcounter.Linq/2.0.0>.

@miyconst please check.

**Comment by miyconst** [comment]
Tested. The `1.0.0` package works with `2.3.1`, while the `2.0.0` package works with `2.4`. Thank you for fixing it. Closing.
