### ISSUE TITLE
LINQ: Support Starcounter.Nova

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#42]
There should be a Starcounter.Linq NuGet package compatible with [Starcounter.Nova](https://github.com/Starcounter/Starcounter.Nova) code host. The package should work under Linux and Windows.

Most likely it will be Starcounter.Linq `3.x.x` with it's own branch.

For now this issue has low priority.

**Comment by un-tone** [comment]
I released Starcounter.Linq v3 package https://github.com/Starcounter/Starcounter.Linq/releases/tag/3.0.1. The source code is in the `nova` branch.

cc @miyconst
