### ISSUE TITLE
Implement GetObjectNo extension method support

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter.Linq#49]
It should be possible to execute such queries:

```cs
DbLinq.Objects<Task>().OrderBy(x => x.GetObjectNo());
```

Currently the `GetObjectNo()` method is not recognized.

**Comment by un-tone** [comment]
@miyconst have you checked it with today releases (1.0.4, 2.0.4, 3.0.4)? I resolved the issue #47 today. At least this one is a duplicate.

**Comment by miyconst** [comment]
Thanks @un-tone, it works with `Starcounter.Linq.2.0.4`.
