### ISSUE TITLE
Obtaining SQL from `IQueryable`

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter.Linq#54]
AFAIK there is no way to get a SQL query from an `IQueryable`. It would be convenient to have this feature, especially since our Linq implementation is young and immature and often needs debugging. I think providing `ToString` implementation for our `IQueryable` would be a good way to do that

**Comment by un-tone** [comment]
Implemented in [1.2](https://github.com/Starcounter/Starcounter.Linq/releases/tag/1.2.0), [2.2](https://github.com/Starcounter/Starcounter.Linq/releases/tag/2.2.0), [3.2](https://github.com/Starcounter/Starcounter.Linq/releases/tag/3.2.0).
