### ISSUE TITLE
Where with object as an argument returns invalid data

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Starcounter.Linq#55]
I have query that should return products, that group is not the same as group that I'm giving to the query (`group` is also a `Product`):
`DbLinq.Objects<Product>().Where(prod => prod.ProductGroup != group && prod != group);`

With database state like this:
![image](https://user-images.githubusercontent.com/25042256/44727445-57f3fb80-aada-11e8-9a30-4b2f3a9217ed.png)

query for test1 should return test3, since its not in this group and its not this group, but it doesn't return anything. More interestingly, when I launch the query for test3, I'll recieve test2 but not test1. Seems like it returns objects that has ProductGroup different but not null, instead of returning both.

**Comment by un-tone** [comment]
It's a bug in QP. I created an issue https://github.com/Starcounter/Home/issues/437 for it.

**Comment by un-tone** [comment]
I should also note that this bug could be fixed only in SC 2.4, so for Starcounter.Linq it will be fixed only in 2.* and 3.* versions.

**Comment by un-tone** [comment]
Temporary workaround: `DbLinq.Objects<Product>().Where(prod => (prod.ProductGroup == null || prod.ProductGroup != group) && prod != group);`

**Comment by miyconst** [comment]
This is not an issue, but rather a desired behavior. The detailed explanation is available here - [SQL comparison failed](https://github.com/Starcounter/Home/issues/437#issuecomment-417253785).
