### ISSUE TITLE
"Incorrect number of SQL parameters" error when method Contains is used on the list of objects.

### ISSUE THREAD

**Issue by kegor** [Starcounter/Starcounter.Linq#57]
Initially was met here https://github.com/Starcounter/Showroom/pull/31#discussion_r214312549, for now work-around with the list of the Ids is used.

**Comment by un-tone** [comment]
@kegor could you please provide steps for reproducing?

**Comment by kegor** [comment]
@un-tone, sorry for the late answer, for now i only can assume that i tried to use following query:
```
this.DivisionProductsDataTable = new DataTableBuilder<DivisionProductsTableItemPage>()
                .WithDataSource(DbLinq.Objects<Product>().Where(x => assignedProducts.Contains(x)), data => data.WithConverter(DivisionProductDetailRow))
```
instead of:
```
this.DivisionProductsDataTable = new DataTableBuilder<DivisionProductsTableItemPage>()
                .WithDataSource(DbLinq.Objects<Product>().Where(x => assignedProductsNo.Contains(x.GetObjectNo())), data => data.WithConverter(DivisionProductDetailRow))
```
on the lines mentioned in the comment from the issue description.

Regarding the steps, i think that this issue can be reproduced without using `UniDataTable` but with just similar query to the arbitrary DB entities.

**Comment by un-tone** [comment]
Fixed. @kegor please check it with version 2.4.1
