### ISSUE TITLE
Add to Bifrost Nova integration builds

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Starcounter.Linq#69]
Noticed in #68, Starcounter.Linq isn't configured with Bifrost. It would be useful if it was so that we can ensure it works with the latest Nova at all times.

CC @ubbeK

**Comment by ubbeK** [comment]
I am wondering when `Starcounter.Linq` should be built/tested/packaged. Who is consuming it in NovaIntegration build?

**Comment by ubbeK** [comment]
I added the Starcounter.Linq target at the end of all Nova builds.

I consider this issue to be implemented, please reopen if any changes are needed.
