### ISSUE TITLE
Mitigate performance loss using compiled queries

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Starcounter.Linq#70]
This investigation https://github.com/Starcounter/Blending/pull/402#issuecomment-449346246 shows us that compiled queries spend much time doing something unexpected. It should definitely work faster that ad-hoc queries. The case must be investigated.

**Comment by miyconst** [comment]
@un-tone would you have a chance to investigate it?

**Comment by un-tone** [comment]
I found out that the issue with compiled query appears only on first call. The following calls work well and are comparable with SQL executing.

  | SQL | Ad-hoc | Compiled
-- | -- | -- | --
First call | 00:00,207 | 00:00,626 | 00:02,152
Iterated 500 | 00:00,162 | 00:00,495 | 00:00,176
Iterated 5000 | 00:02,032 | 00:05,338 | 00:02,033

I can note that the issue does not appear so noticably when obtaining a collection, i.e. using `.ToList()` method for obtaining data. In the tests we used `.FirstOrDefault()`.

<details>
 <summary>Test app source code</summary>

```cs
[Database]
public class C1
{
    public string Name { get; set; }
    public int Value { get; set; }
    public DateTime Created { get; set; }
    public string Token { get; set; }
    public string Tag { get; set; }
}

class Program
{
    public const int PopulationNumber = 1000_000;
    public const int TestIterationNumber = 5000;

    static void Main()
    {
        Handle.GET("/clear", () =>
        {
            Db.Transact(() =>
            {
                Db.SlowSQL($"DELETE FROM {typeof(C1)}");
            });
            return "cleared";
        });

        Handle.GET("/populate", () =>
        {
            Db.Transact(() =>
            {
                for (int i = PopulationNumber; i > 0; i--)
                {
                    _ = new C1
                    {
                        Created = DateTime.UtcNow, Value = i, Name = "name_", Tag = "tag_", Token = "token_"
                    };
                }
            });
            return "populated";
        });

        Handle.GET("/test-sql-1", () => RunTest(1, "typed sql query", CallSql));
        Handle.GET("/test-adhoc-1", () => RunTest(1, "ad-hoc query", CallAdHoc));
        Handle.GET("/test-compiled-1", () => RunTest(1, "compiled query", CallCompiled));

        Handle.GET("/test-sql", () => RunTest(TestIterationNumber, "typed sql query", CallSql));
        Handle.GET("/test-adhoc", () => RunTest(TestIterationNumber, "ad-hoc query", CallAdHoc));
        Handle.GET("/test-compiled", () => RunTest(TestIterationNumber, "compiled query", CallCompiled));
    }

    private static string RunTest(int iterationsCount, string testName, Action<int> action)
    {
        var timer = Stopwatch.StartNew();
        for (int i = 0; i < iterationsCount; i++)
        {
            action(i);
        }
        timer.Stop();
        return $"{testName} tested: {timer.Elapsed:g}";
    }

    private static void CallSql(int i)
    {
        C1 _ = Db.SQL<C1>($"select c from {typeof(C1)} c where c.{nameof(C1.Value)} = ? and " +
                          $"c.{nameof(C1.Name)} = ? and c.{nameof(C1.Tag)} = ? and " +
                          $"c.{nameof(C1.Token)} = ?", i, "name_", "tag_", "token_").FirstOrDefault();
    }

    private static void CallAdHoc(int i)
    {
        C1 _ = Objects<C1>().FirstOrDefault(x => x.Value == i && x.Name == "name_" && x.Tag == "tag_" && x.Token == "token_");
    }

    private static readonly Func<int, string, string, string, C1> Query =
        CompileQuery((int val, string name, string tag, string token) =>
        Objects<C1>().FirstOrDefault(x => x.Value == val && x.Name == name && x.Tag == tag && x.Token == token));

    private static void CallCompiled(int i)
    {
        C1 _ = Query(i, "name_", "tag_", "token_");
    }
}
```

</details>

-----

So, now I'll investigate why compiled queries spend so much time on the first call. Firstly, what we know, the following calls use already cached on the QP level query plans. But even so, for some reason, it costs much more then for executing SQL and ad-hoc queries.

**Comment by un-tone** [comment]
For compiled queries SC.Linq adds extra parentheses in the condition and this is very significant for performance. I created a new issue for it https://github.com/Starcounter/level1/issues/4864. In SC.Linq I'll fix such redundant parentheses adding.

**Comment by un-tone** [comment]
Reopening. Need to minimize the number of parentheses. For instance, in the query `SELECT A FROM "ScLinq70"."AttachmentRule" A WHERE ((((A."Uri" = ?) AND (A."AppName" = ?)) AND (A."Contexts" = ?)) AND (A."Token" = ?))` all the parentheses are redundant.

**Comment by un-tone** [comment]
Done. Published The updated packages (versions *.3.3)
