### ISSUE TITLE
Can't call string.Compare method in the query

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Starcounter.Linq#79]
I'm trying to run such query:
```
                return data.Where(person => string.Compare(person.Email.Address, filter.Value,
                                                CultureInfo.CurrentCulture, CompareOptions.IgnoreNonSpace) == 0);
```
But I'm recieving an exception:
```
System.NotSupportedException: Method call is not supported
	   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitBinaryEquality(Expression left, Expression right, QueryBuilder`1 state, Boolean isEqualsSign)
	   at Starcounter.Linq.Visitors.WhereVisitor`1.VisitBinary(BinaryExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.RootVisitor`1.VisitWhere(Expression expression, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.RootVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.Visitors.RootVisitor`1.VisitMethodCall(MethodCallExpression node, QueryBuilder`1 state)
	   at Starcounter.Linq.QueryContext`1.Execute[TResult](Expression expression)
	   at Starcounter.Linq.QueryProvider.System.Linq.IQueryProvider.Execute[T](Expression expression)
	   at Starcounter.Linq.Queryable`1.GetEnumerator()
	   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
```

Is it possible to workaround this or have support for this method in our library? CC: @un-tone

**Comment by un-tone** [comment]
@PatrykSzwer unfortunately, SC SQL does not support options for string comparisons. So such `string.Compare` method doesn't make sense in this case since we just can't translate that options into SQL.

**Comment by PatrykSzwer** [comment]
Do you have any better idea of how to implement such case described here: https://github.com/Starcounter/Starcounter.Uniform/issues/19 ?

**Comment by un-tone** [comment]
In the same way, like if you used SQL query with `Db.SQL` method - with filtering after retrieving data, e.g.
```cs
return data.ToList()
    .Where(person => string.Compare(person.Email.Address, filter.Value,
                                    CultureInfo.CurrentCulture, CompareOptions.IgnoreNonSpace) == 0);
```

**Comment by PatrykSzwer** [comment]
Thank you for the solution, I think it can be closed since it will never be fixed but the workaround was proposed.

**Comment by miyconst** [comment]
@PatrykSzwer, @un-tone, @warpech, I don't think this is a proper solution for the problem.

Calling `.ToList` on an `IQueriable` will execute the SQL query and lift **all** rows from the database into CLR. Every further filtering will happen in CLR.

The string filtering is way more efficient on the database level, if an index can be utilized. Lifting filtering to the CLR level, removes the index usage possibility.

The diacritics behavior shall be controlled by the database collation settings, unfortunately, currently there is no way to have different collation for different tables / columns, only per database.

Still, filtering can be done on the database level with usage of a computed property. For example:

```cs
using System;
using System.Text;
using System.Globalization;

[Database]
public class Book
{
    public string Name { get; set; }

    public string NameFiltrable
    {
        get
        {
            string normalizedString = this.Name.Normalize(NormalizationForm.FormD);
            StringBuilder sb = new StringBuilder();

            foreach (char c in normalizedString)
            {
                UnicodeCategory unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);

                if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                {
                    sb.Append(c);
                }
            }

            string result = sb.ToString().Normalize(NormalizationForm.FormC);

            return result;
        }
    }
}
```

Even though we currently don't support indexes over computed properties, this have the following benefits:

- Does not lift all rows with `FETCH X` queries.
- We plan to provide support for indexing over computed properties.
- All follow up filters can be executed on the database side as well.
- The computed property can always be replaced with a real property, which will copy the main value without diacritics for indexing and performance.

----------

*P.S. The provided solution is shamelessly copied from:*

- [stackoverflow.com: How do I remove diacritics (accents) from a string in .NET?](https://stackoverflow.com/questions/249087/how-do-i-remove-diacritics-accents-from-a-string-in-net)
- [archives.miloush.net: Stripping diacritics....](http://archives.miloush.net/michkap/archive/2005/02/19/376617.html)

**Comment by miyconst** [comment]
I have reopened a wrong issue. Closing this one.
